### ISSUE TITLE
Click here if the latest search engine update broke your EhViewer

### ISSUE THREAD

**Issue by jtm666** [exzhawk/EhViewer#20] opened 2022-11-04 13:25 UTC
Found another version that works: https://github.com/xiaojieonly/Ehviewer_CN_SXJ
You can change the language setting at: top left corner > gear icon > android icon > the 7th option (App XXX)

**Comment by uNderdog101** [comment] 2022-11-04 13:41
Thanks for the alternative, but I'm gonna wait a while and see if the seemingly related commits Exzhawk made 2 days ago (after the issue appeared) make their way into a compiled release 1.7.11, since I've never successfully migrated smoothly from one fork to another, always losing my favorite searches.

**Comment by Shigbeard** [comment] 2022-11-04 20:36
@uNderdog101 I built this from source earlier today - the commits he made do not address the new search engine.

**Comment by uNderdog101** [comment] 2022-11-04 20:48
@Shigbeard 
Then that's just really weird timing. No commits for over a year, then it breaks, and three commits come hours after it does so, but does not address the breaking.

**Comment by abvgdeyoj** [comment] 2022-11-07 21:49
Duplicate of #19

**Comment by abvgdeyoj** [comment] 2022-11-14 18:30
Solved with https://github.com/exzhawk/EhViewer/commit/441fdbb

**Comment by gammesB** [comment] 2022-11-16 19:50
@abvgdeyoj not fully. the page count can't be loaded yet.
So if you click on the bottom right plus on and then on the "go to" button you can only choose from the pages you already scrolled through(so start it will say-1 after some scrolling page 3 etc.) while there are way more.
So if a search result has 500 pages it will still only show -1 and you can't just fill in a page it doesn't know

**Comment by exzhawk** [comment] 2022-11-21 14:48
@gammesB fixed in 5671c8a8341edf7a2b324ff7a20b3d55d283d1a5

**Closed as completed by exzhawk** 2022-11-21 14:48 UTC
